<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>magnolia-netflix-hollow</artifactId>
    <groupId>org.formentor.magnolia</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <artifactId>netflix-hollow-producer</artifactId>
  <packaging>jar</packaging>
  <name>netflix-hollow-producer Magnolia Module</name>
  <!--
  <description>Please uncomment and fill in ...</description>
  -->

  <dependencies>
    <!-- Netflix Hollow -->
    <dependency>
      <groupId>com.netflix.hollow</groupId>
      <artifactId>hollow</artifactId>
      <version>7.15.1</version>
    </dependency>
    <dependency>
      <groupId>info.magnolia</groupId>
      <artifactId>magnolia-core</artifactId>
    </dependency>

    <dependency>
      <groupId>info.magnolia.types</groupId>
      <artifactId>magnolia-content-types</artifactId>
    </dependency>
    <dependency>
      <groupId>info.magnolia.types</groupId>
      <artifactId>magnolia-content-types-jcr</artifactId>
    </dependency>
    
    <!-- TEST -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

</project>
